config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"
  post "/send", to: "home_page#send_mail"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/send_mail.rb
class SendMail < ApplicationRecord
  before_save :downcase_email

  def downcase_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
    @send_mail = SendMail.new
  end

  def send_mail
    @send_mail = SendMail.new send_mail_params
    if @send_mail.save
      SendMailer.send_mail(@send_mail).deliver_now
      flash[:success] = "Email sent successfully!"
      redirect_to root_path
    else
      flash[:danger] = "Email sending failed!"
      render :home
    end
  end

  private
  def send_mail_params
    params.require(:send_mail).permit :email, :content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home_page/home.html.erb
<div class="container mt-5">
  <div class="container-fluid">
    <div class="card w-75 mx-auto shadow-lg">
      <div class="card-body">
        <h1 class="card-title text-center">Send Mail</h1>
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
              <%= message %>
            </div>
          <% end %>
          <%= form_for @send_mail, url: send_path do |f| %>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, size: "10x10", class: "form-control" %>
            </div>
            <%= f.submit "Send", class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Send Mail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>